In [1]:
import pandas as pd

In [6]:
pd_series = pd.Series(
    [1000,2000,3000,4000]
)

In [9]:
print(pd_series)
print(type(pd_series))

0    1000
1    2000
2    3000
3    4000
dtype: int64
<class 'pandas.core.series.Series'>


In [11]:
pd_series = pd.Series(
    [5000,6000,7000,8000],
    index = ["아메리카노", "카페라떼", "카푸치노", "카페모카"]
)

In [16]:
print(pd_series)
print(pd_series['아메리카노'])
print(pd_series[0]) # warning

아메리카노    5000
카페라떼     6000
카푸치노     7000
카페모카     8000
dtype: int64
5000
5000


C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_11980\3802943974.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(pd_series[0]) # warning


In [ ]:
print(pd_series.values)
print(type(pd_series.values)) # type numpy

[5000 6000 7000 8000]
<class 'numpy.ndarray'>


In [20]:
print(pd_series.index)
print(type(pd_series.index))

Index(['아메리카노', '카페라떼', '카푸치노', '카페모카'], dtype='object')
<class 'pandas.core.indexes.base.Index'>


In [ ]:
pd_series['아메리카노'] = 5500 # 대입 연산 가능

In [26]:
pd_series

아메리카노    5500
카페라떼     6000
카푸치노     7000
카페모카     8000
dtype: int64

In [32]:
pd_series.index = ['아메리카노', '카페라떼', '카푸치노', '마키아또']

In [34]:
pd_series

아메리카노    5500
카페라떼     6000
카푸치노     7000
마키아또     8000
dtype: int64

In [46]:
pd_df = pd.DataFrame(data=[
    [100,200,300],
    [400,500,600]
])
pd_df

0    1    2
0  100  200  300
1  400  500  600

In [53]:
print(pd_df.values)
print(pd_df.index)
print(pd_df.columns)

[[100 200 300]
 [400 500 600]]
RangeIndex(start=0, stop=2, step=1)
RangeIndex(start=0, stop=3, step=1)


In [73]:
pd_df.rename(
    columns={
        0:"a",
        1:"b",
        2:"c"
    },
    index={
        0:"000",
        1:"001"
    },
    inplace=True
)

In [ ]:
df = pd_df # 같이 바뀐다다

a    b    c
00  100  200  300
01  400  500  600

In [ ]:
df.rename(
    columns={
        "a":"A"
    },
    inplace=True # df = df.rename 으로 할당한 것과 같다
)

In [79]:
df

A    b    c
00  100  200  300
01  400  500  600

In [80]:
pd_df


A    b    c
00  100  200  300
01  400  500  600

In [84]:
# 2차원 딕셔너리와 리스트를 데이터 프레임으로
data = {
    'name': ['a','b','c','d'],
    'age': [1,2,3,4]
}

df2 = pd.DataFrame(data)
df2

name  age
0    a    1
1    b    2
2    c    3
3    d    4